config/routes.rb
Pain::Application.routes.draw do
  get "pages/home"

  get "pages/contact_us"

  get "pages/about_us"

  get "users/your_account"
  get "users/your_ads"

  devise_for :users

  resources :properties, :controller => :properties, :type => 'Property', only: [:index, :show] do
    get 'autocomplete_location_city', on: :collection
    get 'listing_new_property', on: :collection
    post 'enter_new_property_details', on: :collection
  end
  resources :residential, :controller => :properties, :type => 'Residential'
  resources :independent_houses, :controller => :properties, :type => 'IndependentHouse'
  resources :apartment_houses, :controller => :properties, :type => 'ApartmentHouse'
  resources :villas, :controller => :properties, :type => 'Villa'
  resources :residential_lands, :controller => :properties, :type => 'ResidentialLand'
  resources :commercial, :controller => :properties, :type => 'Commercial'
  resources :office_spaces, :controller => :properties, :type => 'OfficeSpace'
  resources :show_rooms, :controller => :properties, :type => 'ShowRoom'
  resources :industrial_lands, :controller => :properties, :type => 'IndustrialLand'
  resources :hotels, :controller => :properties, :type => 'Hotel'
  resources :agricultural_land, :controller => :properties, :type => 'AgriculturalLand'

  root :to => 'pages#home'

end

app/models/property.rb
class Property < ActiveRecord::Base
  attr_accessible  :title, :description, :dimensions, :dimensions_unit, :price, :address_attributes, :image_attributes, :amenity_list
  belongs_to :user
  has_one :address, as: :addressable, dependent: :destroy
  has_one :image, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :image
  before_create :assign_user, :generate_code
  acts_as_taggable_on :amenities
  monetize :price_cents, as: :price
  #monetize :maintenance_charge_cents, as: :maintenance_charge
  serialize :additional_details
  private
    def assign_user
      self.user = current_user
    end

    def generate_code
      self.code = "PA#{Time.new.to_i + Property.count}"
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  #load_and_authorize_resource :except => [:autocomplete_location_city]
  before_filter :authenticate_user!, :except => [:index, :autocomplete_location_city]
  before_filter :set_current_user
  autocomplete :location, :city, :scopes => [:unique_cities], :full => true
  # GET /properties
  # GET /properties.json
  def index
    Property.first
    params[:q] = view_context.convert_price_to_price_cents(params[:q])
    @properties = property_type.search(params[:q]).result.order('created_at desc').page(params[:page]).per(5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @properties }
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = property_type.find(params[:id])
    @address = @property.address
    @gmap_json = @address.to_gmaps4rails

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  def listing_new_property

  end

  def enter_new_property_details
    eval("redirect_to new_#{params[:select_property_type].underscore}_path")
  end

  # GET /properties/new
  # GET /properties/new.json
  def new
    @property = property_type.new
    @property.build_address
    @property.build_image
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/1/edit
  def edit
    @property = property_type.find(params[:id])
    @property.build_image
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = property_type.new(params[property_params])

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render json: @property, status: :created, location: @property }
      else
        raise @property.errors.full_messages.inspect
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.json
  def update
    @property = property_type.find(params[:id])

    respond_to do |format|
      if @property.update_attributes(params[property_params])
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property = property_type.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :no_content }
    end
  end

  private

  def property_type
    params[:type].constantize
  end
  
  def property_params
    params[:type].underscore.to_sym
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
	def convert_price_to_price_cents(q)
		return q if q.blank? || q[:price_lteq].blank? && q[:price_gteq].blank?

		if q[:price_lteq].present?
			price = q.delete(:price_lteq).to_i
      q[:price_cents_lteq] = price * 100
    end
    if q[:price_gteq].present?
			price = q.delete(:price_gteq).to_i
      q[:price_cents_gteq] = price * 100
    end
    q
	end
end

app/views/properties/_form.html.erb
<%= form_for(@property, :html => { :multipart => true, :class => 'custom'  }) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='property-address property-section-box'>
    <h5 class='sub-title'>Property Address</h5>
    <div class='address-details'>
      <%= f.fields_for :address do |address| %>
        <div class='field marginr-50'>
          <%= address.label :address %>
          <%= address.text_area :address %>
        </div>
        <div class='clearfix'>
          <div class="float-left field">
            <%= address.label :city %>
            <%= address.text_field :city%>
          </div>
          <div class="float-left field marginl-50">
            <%= address.label :area, 'Area / Landmark' %>
            <%= address.text_field :area %>
          </div>
        </div>
        <div class='clearfix'>
          <div class="float-left field">
            <%= address.label :state %>
            <%= address.text_field :state %>
          </div>
          <div class="float-left field marginl-50">  
            <%=address.label :pincode %>
            <%= address.text_field :pincode %>
          </div>
        </div>
      <% end %>
      <div class='clearfix'> </div>
    </div>
  </div>
  <div class='property-section-box'>
    <h5 class='sub-title'>Property Details</h5>
    <div class="field">
      <%= f.label :title, 'Listing Title' %>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <% if File.exists?(File.join(File.dirname(__FILE__), "_#{params[:type].underscore}_options.html.erb")) %>
      <%= render "#{params[:type].underscore}_options", :f => f %>
    <% else %>
      <div class="field">
        <%= f.label :dimensions %>
        <%= f.text_field :dimensions %>
      </div>
      <div class="field">
        <%= f.label :dimensions_unit, 'Unit' %>
        <%= f.text_field :dimensions_unit %>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :price %>
      <%= f.text_field :price %>
    </div>
    <%= f.fields_for :image do |image| %>
      <div class='field'>
        <%= image.label :image %>
        <%= image.file_field :image %>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :amenity_list, 'Amenities (Seperated by commas)' %>
      <%= f.text_field :amenity_list %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit :class => 'small button' %>
  </div>
<% end %>

app/views/properties/_independent_house_options.html.erb
<%= render 'residential_house_options', :f => f %>

app/views/properties/_residential_house_options.html.erb
<div class="field">
  <%= f.label :dimensions, 'Buit-up Area' %>
  <%= f.text_field :dimensions %>
</div>
<div class="field">
  <%= f.label :dimensions_unit, 'Unit' %>
  <%= f.text_field :dimensions_unit %>
</div>
<div class="field">
  <%= f.label :bedrooms %>
  <%= f.select :bedrooms, options_for_select(Residential::BEDROOMS.zip(Residential::BEDROOMS)), :class => 'customDropdown' %>
</div>

app/views/properties/_search.html.erb
<div class='property-search'>
	<%= form_tag properties_path, {:method => :get, :name => :q, :class=> 'custom'} do %>
		<div class='row'>
			<div class="large-12 columns">
				<%= label_tag 'q[type_eq]', 'Property Type' %>
				<%= select_tag 'q[type_eq]', options_for_select([['All Properties',''],['Apartments', 'Apartment'],['Independent Houses', 'IndependentHouse'], ['Villas', 'Villa']]), :id => 'customDropdown' %>
			</div>
		</div>
		<div class='row'>
			<div class="large-12 columns">
				<%= label_tag 'q[address_city_eq]', 'City' %>
				<%= autocomplete_field_tag 'q[address_city_eq]', nil, autocomplete_location_city_properties_path, :min_length => 0 , :id => 'auto-complete-city' %>
			</div>
		</div>
		<div class='row'>
			<div class='large-6 columns'>
				<%= label_tag 'q[price_gteq]', 'Price From' %>
				<%= text_field_tag 'q[price_gteq]' %>
			</div>
			<div class='large-6 columns'>
				<%= label_tag 'q[price_lteq]', 'Price To' %>
				<%= text_field_tag 'q[price_lteq]' %>
			</div>
		</div>
		<div class='row'>
			<div class="large-12 columns">
	      <%= submit_tag 'Search', :class => 'small button' %>
	    </div>
	  </div>
	<% end %>
</div>

app/views/properties/edit.html.erb
<div id='new-property'>
	<div class='row'>
	  <div class='large-12 columns'>
	    <h3 class='page-title'>Editing property</h3>
	  </div>
	</div>
	<div class='row'>
		<div class='large-12 columns'>
	    <%= render 'form' %>
	  </div>
	</div>
</div>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<div id='property-index'>
  <div class='row'>
    <div class='large-2 columns'>
      <div class='property-gallery' style='border: 1px solid #4d4d4d; width:100% !important;'>
        <h6>Property Gallery</h6>
      </div>
    </div>
    <div class='large-10 columns'>
      <div class='property-list'>
        <h4><%= "Listing #{((params[:q] && params[:q][:type_eq])|| params[:type]).underscore.titlecase} Properties" %></h4>
        <%= paginate @properties %>
        <% @properties.each do |property| %>
          <div class='property-listing-large property-listing'>
            <div class='float-left photo col'>
              <%= image_tag (property.image.present? ? property.image.image.url(:thumb) : 'no_image.jpg') %>
            </div>
            <div class='float-left property-info col'>
              <dl class='float-left col main-data'>
                <dt class='code'>Code: <%= property.code %></dt>
                <dt class='property-type'><%= property.type.titlecase %></dt>
                <dt class='area'><%= property.dimensions %></dt>
                <dt class='price'><%= property.price.format %></dt>
              </dl>
              <dl class='float-left data'>
                <dt class='code'><%= property.title %></dt>
                <p><%= truncate property.description, :length => 150 %></p>
                <dt><%= link_to 'Show Details', eval("#{property.type.underscore}_path(property)"), :class => 'small button' %></dt>
              </dl>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/properties/listing_new_property.html.erb
<div id="listing-new-property">
  <div class='row'>
    <div class='large-12 columns'>
      <div class='listing-banner'>
        <div class='title'>
          <h3>List your property for FREE!<sup>*</sup></h3>
        </div>
        <ul class='list-msg circle'>
          <li>Free exposure to millions of people searching for homes</li>
          <li>Real time leads from people interested in your listings</li>
          <li>Engaging listings with your contact info, unlimited photos, and open homes times</li>
          <li>Reporting of views, clicks and leads for all your listings</li>
        </ul>
      </div>
    </div>
  </div>
  <div class="row">
	  <div class='large-6 columns single-listing'>
	    <div class='content'>
		    <%= form_tag enter_new_property_details_properties_path, :class => 'custom' do %>
		      <h4>Submit a Listing</h4>
	        <p>
	          For sale and rental listings can also be submitted manually. This method is easy and fast - your listing can be live on PropertyAds.in after approving by admin.
	        </p>
	        <div class='property-type'>
	          <%= label_tag :select_property_type, 'Choose Property Type' %>
				    <%= select_tag :select_property_type, options_for_select([['Apartments', 'ApartmentHouse'],['Independent Houses', 'IndependentHouse'], ['Villas', 'Villa']]), :id => 'customDropdown' %>
	        </div>
		      <%= submit_tag 'Enter Property Details', :class => 'small button' %>
	      <% end %>
	    </div>
	  </div>
	  <div class='large-6 columns bulk-listing'>
	  	
	  </div>
  </div>
</div>

app/views/properties/new.html.erb
<div id='new-property'>
	<div class='row'>
	  <div class='large-12 columns'>
	    <h3 class='page-title'>Enter Details of <%= "#{params[:type].titlecase}" %></h3>
	  </div>
	</div>
	<div class='row'>
	  <div class='large-12 columns'>
	    <%= render 'form' %>
	  </div>
	</div>
</div>

app/views/properties/show.html.erb
<div class='property-show'>
  <div class='row'>
    <div class='large-12 columns'>
      <h3><%= @property.title %></h3>
				<p>
				  <b>Description:</b>
				  <%= @property.description %>
				</p>
				<p>
				  <b>Dimensions:</b>
				  <%= @property.dimensions %>
				</p>
				<p>
				  <b>Price:</b>
				  <%= @property.price %>
				</p>
				<%#= gmaps4rails(@gmap_json) %>
				<%= gmaps("markers" => {"data" => @gmap_json}, "map_options" => {"auto_zoom" => false, "zoom" => 13}) %>
				<%= link_to 'Edit', eval("edit_#{params[:type].underscore}_path(@property)") %> |
				<%= link_to 'Back', properties_path %>
    </div>
   </div>
</div>