config/routes.rb
Pain::Application.routes.draw do
  get "pages/home"

  get "pages/contact_us"

  get "pages/about_us"

  get "users/your_account"
  get "users/your_ads"

  devise_for :users

  resources :properties, :controller => :properties, :type => 'Property', only: [:index, :show] do
    get 'autocomplete_location_city', on: :collection
    get 'listing_new_property', on: :collection
    post 'enter_new_property_details', on: :collection
  end
  resources :residential, :controller => :properties, :type => 'Residential'
  resources :independent_houses, :controller => :properties, :type => 'IndependentHouse'
  resources :apartment_houses, :controller => :properties, :type => 'ApartmentHouse'
  resources :villas, :controller => :properties, :type => 'Villa'
  resources :residential_lands, :controller => :properties, :type => 'ResidentialLand'
  resources :commercial, :controller => :properties, :type => 'Commercial'
  resources :office_spaces, :controller => :properties, :type => 'OfficeSpace'
  resources :show_rooms, :controller => :properties, :type => 'ShowRoom'
  resources :industrial_lands, :controller => :properties, :type => 'IndustrialLand'
  resources :hotels, :controller => :properties, :type => 'Hotel'
  resources :agricultural_land, :controller => :properties, :type => 'AgriculturalLand'

  root :to => 'pages#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "PropertyAds" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= stylesheet_link_tag "bjqs" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class='page'>
		  <header class='header'>
		    <div class='top-links'>
		      <div class='logo'><%= link_to(image_tag('c_logo.png', :alt => 'Propertyads', :width => "200px", :height => "100px"), root_path) %></div>
		      <div class='links'>
		        <span><%= link_to 'About Us', pages_about_us_path %></span>
		        <span><%= link_to 'Contact Us', pages_contact_us_path %></span>
		        <% if !user_signed_in? %>
		          <span><%= link_to 'Sign Up', new_user_registration_path %></span>
		        <% end %>
		        <span class='sign-in'>
			        <% if user_signed_in? %>
			          <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
			        <% else %>
			          <%= link_to 'Sign In', new_user_session_path %>
			        <% end %>
			      </span>
		      </div>
			  </div>
			  <div class='nav-menu'>
					<nav class="top-bar">
					  <ul class="title-area">
					    <!-- Title Area -->
					    <li class="name">
					    </li>
					    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
					    <li class="toggle-topbar"><a href="#"><span>Menu</span></a></li>
					  </ul>

					  <section class="top-bar-section">
					    <!-- Left Nav Section -->
					    <ul class="left">
					      <li class="divider"></li>
					      <li class="active"><%= link_to 'Home', root_path %></li>
					      <li class="divider"></li>
					      <li class="has-dropdown"><a href="#">Residential</a>
					        <ul class="dropdown">
					          <!-- <li><label>Dropdown Level 2 Label</label></li> -->
							      <li><%= link_to 'Independent Houses', independent_houses_path %></li>
							      <li class><%= link_to 'Apartment Houses', apartment_houses_path %></li>
							      <li><%= link_to 'Residential Lands', residential_lands_path %></li>
							      <li><%= link_to 'Villas', villas_path %></li>
							      <li class="divider"></li>
                    <li><%= link_to "See all", residential_index_path %></li>
						      </ul>
					      </li>
					      <li class="divider"></li>
					      <li class="has-dropdown"><a href="#">Commercial</a>
					        <ul class="dropdown">
					          <li><a href="#">Office Space</a></li>
						      <li><a href="#">Show rooms</a></li>
						      <li><a href="#">Service Apartments</a></li>
						      <li><a href="#">Hotel</a></li>
						      <li><a href="#">Industrial Land</a></li>
						      <li><a href="#">Agricultural Land</a></li>
						      <li><a href="#">Resorts</a></li>
						      <li class="divider"></li>
	                <li><a href="#">See all</a></li>
						    </ul>
					      </li>
					    </ul>


					    <!-- Right Nav Section -->
					    <ul class="right">
					      <li class="divider"></li>
					      <li><%= link_to 'List Property for FREE*', listing_new_property_properties_path %></li>
					      <li class="divider"></li>
					      <% if user_signed_in? %>
						      <li class="has-dropdown"><a href="#">Welcome <%= truncate(current_user.email, :length => 15) %></a>
						        <ul class="dropdown">
						          <!-- <li><label>Dropdown Level 2 Label</label></li> -->
							        <li class><%= link_to 'Your Account', users_your_account_path %></li>
								      <li><%= link_to 'Your Ads', users_your_ads_path %></li>
							      </ul>
						      </li>
						    <% else %>
						      <li><a href="#">Welcome Guest</a></li>
						    <% end %>
						    <li class="divider"></li>
					    </ul>
					  </section>
					</nav>
				</div>
		  </header>
		  <article class='body'>
	      <%= yield %>
	    </article>
	    <footer class='footer'>
	      <div class = 'row'>
	        <div class = '12-large columns'>
			      <section class='nav-footer'>
			        <ul class="inline-list links">
		            <li><a href="#">About Us</a></li>
							  <li><a href="#">Contact Us</a></li>
							  <li><a href="#">Help</a></li>
							  <li><a href="#">Terms of Use</a></li>
		          </ul>
			      </section>
			    </div>
			  </div>
	    </footer>
	  </div>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "bjqs.min" %>
    <%= yield :scripts %>
  </body>
</html>